const CATEGORY = {
  SHIP: "SHIP", // 舰船
  HIGH_SLOTS_MAIN_WEAPON: "HIGH_SLOTS_MAIN_WEAPON", //高槽/主武器
  MID_SLOTS_SUB_WEAPON: "MID_SLOTS_SUB_WEAPON", // 中槽/副武器
  LOW_SLOTS_ENHANCEMENT: "LOW_SLOTS_ENHANCEMENT", // 低槽/强化
  COMBAT_RIG: "COMBAT_RIG", // 战斗改装件
  ENGINEERING_RIG: "ENGINEERING_RIG", //工程改装件
  STRUCTURE: "STRUCTURE", // 建筑
  MANUFACTURING_MATERIAL: "MANUFACTURING_MATERIAL", // 制造材料
  BLUEPRINT: "BLUEPRINT", // 蓝图
  SHIP_SKIN: "SHIP_SKIN", // 舰船涂装
  OTHER_ITEM: "OTHER_ITEM" // 其他物品
}

const SUB_CATEGORY = {
  // 舰船
  FRIGATE: "FRIGATE", // 护卫舰
  DESTROYER: "DESTROYER", // 驱逐舰
  CRUISER: "CRUISER", // 巡洋舰
  BATTLECRUISER: "BATTLECRUISER", // 战列巡洋舰
  SHUTTLE: "SHUTTLE", // 穿梭机
  INDUSTRIAL_SHIP: "INDUSTRIAL_SHIP", // 工业舰
  BATTLESHIP: "BATTLESHIP", // 战列舰
  // 高槽
  LASER: "LASER",
  RAILGUN: "RAILGUN",
  CANNON: "CANNON",
  DECOMPOSER: "DECOMPOSER",
  MISSILE_LAUNCHER: "MISSILE_LAUNCHER",
  HARVEST_EQUIPMENT: "HARVEST_EQUIPMENT",
  REMOTE_SHIELD_BOOSTER: "REMOTE_SHIELD_BOOSTER",
  REMOTE_ARMOR_REPAIRER: "REMOTE_ARMOR_REPAIRER",
  //中槽
  DRONE: "DRONE",
  ELECTRONIC_WARFARE: "ELECTRONIC_WARFARE",
  ENERGY_NOSFERATU: "ENERGY_NOSFERATU",
  ENERGY_NEUTRALIZER: "ENERGY_NEUTRALIZER",
  SHIELD_FIELD_MODULE: "SHIELD_FIELD_MODULE",
  ARMOR_LINK_MODULE: "ARMOR_LINK_MODULE",
  REMOTE_CAPACITOR_TRANSMITTER: "REMOTE_CAPACITOR_TRANSMITTER",
  GROUP_SHIELD_BOOSTER: "GROUP_SHIELD_BOOSTER",
  GROUP_ARMOR_REPAIRER: "GROUP_ARMOR_REPAIRER",
  GROUP_CAPACITOR_TRANSMITTER: "GROUP_CAPACITOR_TRANSMITTER",
  INTERDICTION_MODULE: "INTERDICTION_MODULE",
  //低槽
  SHIELD_BOOSTER: "SHIELD_BOOSTER",
  SHIELD_EXTENDER: "SHIELD_EXTENDER",
  SHIELD_HARDENER: "SHIELD_HARDENER",
  ARMOR_REPAIRER: "ARMOR_REPAIRER",
  ARMOR_PLATE: "ARMOR_PLATE",
  ARMOR_HARDENER: "ARMOR_HARDENER",
  DAMAGE_CONTROL: "DAMAGE_CONTROL",
  CAPACITOR_BATTERIES: "CAPACITOR_BATTERIES",
  AFTERBURNER: "AFTERBURNER",
  MICROWARPDRIVE: "MICROWARPDRIVE",
  THRUSTER_UPGRADE: "THRUSTER_UPGRADE",
  WEAPON_UPGRADE: "WEAPON_UPGRADE",
  CLOAKING_DEVICE: "CLOAKING_DEVICE",
  //战斗改装件
  WEAPON_RIG: "WEAPON_RIG",
  DRONE_RIG: "DRONE_RIG",
  DEFENSIVE_RIG: "DEFENSIVE_RIG",
  //工程改装件
  NAVIGATION_RIG: "NAVIGATION_RIG",
  ENGINEERING_RIG: "ENGINEERING_RIG",
  ELECTRONIC_RIG: "ELECTRONIC_RIG",
  INDUSTRIAL_RIG: "INDUSTRIAL_RIG",
  //建筑
  STRUCTURE: "STRUCTURE",
  STRUCTURE_MODULE: "STRUCTURE_MODULE",
  //制造材料
  MINERAL: "MINERAL",
  RAW_ORE: "RAW_ORE",
  PLANETARY_RESOURCE: "PLANETARY_RESOURCE",
  SALVAGED_MATERIAL: "SALVAGED_MATERIAL",
  VESSEL_DEBRIS: "VESSEL_DEBRIS",
  DATACORE: "DATACORE",
  //蓝图
  SHIP_BLUEPRINT: "SHIP_BLUEPRINT",
  MODULE_BLUEPRINT: "MODULE_BLUEPRINT",
  DRONE_BLUEPRINT: "DRONE_BLUEPRINT",
  RIG_BLUEPRINT: "RIG_BLUEPRINT",
  STRUCTURE_BLUEPRINT: "STRUCTURE_BLUEPRINT",
}

const SIZE = {
  SMALL: "s",
  MEDIUM: "m",
  LARGE: "l",
}

module.exports = {
  CATEGORY,
  SUB_CATEGORY,
  SIZE
}
